language: cpp
install:
  - sudo pip install cpp-coveralls
script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ./unit_tests
after_success:
  - coveralls --root .. -E ".*third-party.*" -E ".*CMakeFiles.*" -E ".*test/.*.cpp.*"
